name: Release
on:
  push:
    branches:
      - master
    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
    paths:
      - "server/**"
      - ".github/workflows/**"

jobs:
  build-and-deploy-backend:
    name: üõ† Build Backend Image for Prod & Push to Dockerhub
    runs-on: ubuntu-latest
    steps:
        # Checkout Project
      - name: üìö Checkout
        uses: actions/checkout@v2

        # Setup Docker Builder
        # -> The tool we are going to build our Docker Image
        # https://github.com/marketplace/actions/docker-setup-buildx
      - name: üê≥ Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: üê≥ Docker Cache Layer
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: üê≥ Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # https://github.com/marketplace/actions/build-and-push-docker-images
        # https://www.docker.com/blog/docker-v2-github-action-is-now-ga/
      - name: üê≥ Build and push Docker Image to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: server/Dockerfile # Path to the Dockerfile from which to build the Docker Image from (default {context}/Dockerfile)
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: latest # Tag the build with the 'latest' tag (Docker Tags are like tags on GitHub, to differentiate between versions of the same Repository)
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

        # https://www.mikenewswanger.com/posts/2020/docker-image-digests/#:~:text=Docker%20digest%20is%20provided%20as,based%20on%20the%20image%20build.
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
